sonar.projectKey=MuzykantR_python-pytest-testing-project-79
sonar.organization=muzykantr


sonar.sources=hexlet-code/page_loader
sonar.tests=hexlet-code/tests
sonar.language=py
sonar.python.coverage.reportPaths=hexlet-code/coverage.xml

sonar.sourceEncoding=UTF-8
sonar.exclusions=**/tests/**,**/venv/**,**/.git/**,**/__pycache__/**